# Generated by Django 3.1.7 on 2021-04-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210406_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ctegory',
            new_name='category',
        ),
    ]
